name: English Radar

on:
  workflow_dispatch:

  schedule:
    - cron: "0 5 * * *"
    - cron: "0 7 * * *"
    - cron: "0 9 * * *"
    - cron: "0 11 * * *"
    - cron: "0 13 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:

      - name: Get code
        uses: actions/checkout@v4

      - name: Install libraries
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests edge-tts
          
      - name: Run English Radar
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python bot.py
